In [1]:
import numpy as np
kernel = np.array([[1, 0, 0], [0, 1, 0],[0,0,1]])

image=np.array([[75,200,30,70,46,45], [79, 82, 0,150,99, 100],[62,30,12,13,0, 145],  [72,77,255,32,1, 200],[45,200,186,0,16, 150],[178,79,65,177,250, 0]])
print('Original image')
print(image)
print('Kernel')
print(kernel)

Original image
[[ 75 200  30  70  46  45]
 [ 79  82   0 150  99 100]
 [ 62  30  12  13   0 145]
 [ 72  77 255  32   1 200]
 [ 45 200 186   0  16 150]
 [178  79  65 177 250   0]]
Kernel
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [14]:
def myfilter2D(X, H):
    # make sure both X and H are 2-D
    assert( X.ndim == 2)
    assert( H.ndim == 2)

    # get the horizontal and vertical size of X and H
    imageColumns = X.shape[1]
    imageRows = X.shape[0]
    kernelColumns = H.shape[1]
    kernelRows = H.shape[0]

    # calculate the horizontal and vertical size of Y (assume "full" convolution)
    newRows = imageRows - kernelRows + 1
    newColumns = imageColumns - kernelColumns + 1

    # create an empty output array
    Y = np.zeros((newRows,newColumns))

    # go over output locations
    for m in range(newRows):
        for n in range(newColumns):
            # go over input locations
            for i in range(kernelRows):
                for j in range(kernelColumns):
#                     if (m-i >= 0) and (m-i < imageRows ) and (n-j >= 0) and (n-j < imageColumns):
#                         print(m,n,i,j)
                    Y[m,n] = Y[m,n] + H[i,j]*X[m+i,n+j]
                                
        # make sure kernel is within bounds
        # calculate the convolution sum

    return Y

In [15]:
Y = myfilter2D(image,kernel)
print('Output image')
print(Y)

Output image
[[169. 213. 180. 314.]
 [364. 126.  14. 350.]
 [325. 285.  60. 164.]
 [337. 440. 505.  48.]]


In [16]:
def convolution2d(image, kernel, stride, padding):
    image = np.pad(image, [(padding, padding), (padding, padding)], mode='constant', constant_values=0)

    kernel_height, kernel_width = kernel.shape
    padded_height, padded_width = image.shape

    output_height = (padded_height - kernel_height) // stride + 1
    output_width = (padded_width - kernel_width) // stride + 1

    new_image = np.zeros((output_height, output_width)).astype(np.float32)

    for y in range(0, output_height):
        for x in range(0, output_width):
            new_image[y][x] = np.sum(image[y * stride:y * stride + kernel_height, x * stride:x * stride + kernel_width] * kernel).astype(np.float32)
    return new_image

In [28]:
Y2 = convolution2d(image,kernel,1,1)

In [29]:
print('Output image 2')
print(Y2)

Output image 2
[[157. 200. 180. 169. 146.  45.]
 [109. 169. 213. 180. 314. 146.]
 [139. 364. 126.  14. 350. 244.]
 [272. 325. 285.  60. 164. 200.]
 [124. 337. 440. 505.  48. 151.]
 [178. 124. 265. 363. 250.  16.]]


In [50]:
def convolve2d_2(image, kernel):
    """
    This function which takes an image and a kernel and returns the convolution of them.

    :param image: a numpy array of size [image_height, image_width].
    :param kernel: a numpy array of size [kernel_height, kernel_width].
    :return: a numpy array of size [image_height, image_width] (convolution output).
    """
    # Flip the kernel
    kernel = np.flipud(np.fliplr(kernel))
    # convolution output
    output = np.zeros_like(image)
    print('image shape: ', image.shape)
    print(image)
    # Add zero padding to the input image
    image_padded = np.zeros((image.shape[0] + 2, image.shape[1] + 2))
    image_padded[1:-1, 1:-1] = image
    print('image_padded shape: ', image_padded.shape)
    print(image_padded)
    # Loop over every pixel of the image
    for x in range(image.shape[1]):
        for y in range(image.shape[0]):
#             element-wise multiplication of the kernel and the image
            output[y, x]=(kernel * image_padded[y: y+3, x: x+3]).sum()
#             print(y,x)
#             print(kernel)
#             print(image_padded[y: y+3, x: x+3])
            
#             break

    return output

In [51]:
image_sharpen = convolve2d_2(image, kernel=kernel)

image shape:  (6, 6)
[[ 75 200  30  70  46  45]
 [ 79  82   0 150  99 100]
 [ 62  30  12  13   0 145]
 [ 72  77 255  32   1 200]
 [ 45 200 186   0  16 150]
 [178  79  65 177 250   0]]
image_padded shape:  (8, 8)
[[  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  75. 200.  30.  70.  46.  45.   0.]
 [  0.  79.  82.   0. 150.  99. 100.   0.]
 [  0.  62.  30.  12.  13.   0. 145.   0.]
 [  0.  72.  77. 255.  32.   1. 200.   0.]
 [  0.  45. 200. 186.   0.  16. 150.   0.]
 [  0. 178.  79.  65. 177. 250.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]]


In [47]:
print('Output image 2')
print(image_sharpen)

Output image 2
[[157 200 180 169 146  45]
 [109 169 213 180 314 146]
 [139 364 126  14 350 244]
 [272 325 285  60 164 200]
 [124 337 440 505  48 151]
 [178 124 265 363 250  16]]


In [4]:
import scipy.signal

In [5]:
res = scipy.signal.convolve2d(image, kernel, mode='valid', boundary='fill', fillvalue=0)
print(res)

[[169 213 180 314]
 [364 126  14 350]
 [325 285  60 164]
 [337 440 505  48]]


In [6]:
res2 = scipy.signal.convolve2d(image, kernel, mode='same', boundary='fill', fillvalue=0)
print(res2)

[[157 200 180 169 146  45]
 [109 169 213 180 314 146]
 [139 364 126  14 350 244]
 [272 325 285  60 164 200]
 [124 337 440 505  48 151]
 [178 124 265 363 250  16]]


In [ ]:
def convolve2d_2(image, kernel):
    """
    This function which takes an image and a kernel and returns the convolution of them.

    :param image: a numpy array of size [image_height, image_width].
    :param kernel: a numpy array of size [kernel_height, kernel_width].
    :return: a numpy array of size [image_height, image_width] (convolution output).
    """
    # Flip the kernel
    kernel = np.flipud(np.fliplr(kernel))
    # convolution output
    output = np.zeros_like(image)
    print('image shape: ', image.shape)
    print(image)
    # Add zero padding to the input image
    image_padded = np.zeros((image.shape[0] + 2, image.shape[1] + 2))
    image_padded[1:-1, 1:-1] = image
    print('image_padded shape: ', image_padded.shape)
    print(image_padded)
    # Loop over every pixel of the image
    for x in range(image.shape[1]):
        for y in range(image.shape[0]):
            # element-wise multiplication of the kernel and the image
#             output[y, x]=(kernel * image_padded[y: y+3, x: x+3]).sum()
            print(y,x)
            print(kernel)
            print(image_padded[y: y+3, x: x+3])
            
            break

    return output